"""Add Summary column to content

Revision ID: 005a7387fadb
Revises: d8ccba26a441
Create Date: 2026-08-26 17:10:42.102085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005a7387fadb'
down_revision = 'd8ccba26a441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ThumbnailURL', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('ThumbnailURL')
        batch_op.drop_column('Summary')

    # ### end Alembic commands ###
