"""Add Duration column to content table

Revision ID: 7760eec6ebb1
Revises: 
Create Date: 2026-08-25 05:21:24.438385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7760eec6ebb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ViewsCount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Hashtags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('Hashtags')
        batch_op.drop_column('ViewsCount')
        batch_op.drop_column('Duration')

    # ### end Alembic commands ###
